runtime: python37

handlers:
  - url: /images
    static_dir: dist/images

  - url: /v-1589301622195
    static_dir: dist/v-1589301622195

  - url: /conf.json
    static_files: dist/conf.json
    upload: dist/conf.json

  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html